#! /usr/bin/env python3
import json
import requests

# Define the path for README.md
readme_file_path = "README.md"

# Fetch the JSON content from the Gist URL
gist_url = "https://gist.githubusercontent.com/junaid18183/8896f09cd09bec2ddcffb6a41b4f3eb0/raw/"
response = requests.get(gist_url)
response.raise_for_status()  # Raises an HTTPError for bad responses

data = response.json()

bio = data.get("basics", {})
work = data.get("work", [])
skills = data.get("skills", [])
projects = data.get("projects", [])
certificates = data.get("certificates", [])

lines = []

# Header
lines.append(f"# 👋 Hi, I'm {bio.get('name')}")
lines.append(bio.get("summary", ""))
lines.append("")

# Work
lines.append("## 💼 Work Experience")
for job in work:
    lines.append(f"- **{job['position']}** at **{job['company']}** ({job['startDate']} – {job.get('endDate', 'Present')})")
    if job.get("summary"):
        lines.append(f"  - {job['summary']}")
lines.append("")

# Skills
lines.append("## 🛠 Skills")
for skill in skills:
    lines.append(f"- **{skill['name']}**: {', '.join(skill['keywords'])}")
lines.append("")

# Certificates
lines.append("## 🚀 Certificates")
for certificate in certificates:
    lines.append(f"- **{certificate['name']}** from **{certificate['issuer']}** ({certificate['date']}) – {certificate.get('url', '')}")

lines.append("## 🚀 Projects")
for project in projects:
    lines.append(f"- [{project['name']}]({project['url']}) – {project['description']}")

lines.append("## 📬 Connect with Me")
lines.append(f"- [LinkedIn](https://linkedin.com/in/junaid18183)")
lines.append(f"- [GitHub](https://github.com/junaid18183)")
lines.append(f"- [Twitter](https://twitter.com/junaid18183)")

lines.append("## 📬 Repositories")
lines.append(f"- [Repositories](https://github.com/junaid18183?tab=repositories&q=&type=public&language=&sort=)")

lines.append("## 📊 GitHub Stats")
lines.append(f"![GitHub Stats](https://github-readme-stats.vercel.app/api?username=junaid18183&count_private=true&show_icons=true&include_all_commits=true)")

# Write to README.md
with open(readme_file_path, "w") as f:
    f.write("\n".join(lines))

# Add a footer
with open(readme_file_path, "a") as f:
    f.write("\n---\n")
    f.write("Generated by [generate_readme.py]()\n")

print(f"{readme_file_path} generated successfully!")
