name: Generate Profile README

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi

    - name: Generate README.md
      run: |
        pip install requests
        python .github/generate_readme.py

    - name: Commit and push changes
      env:
        GIT_AUTHOR_NAME: "GitHub Actions"
        GIT_AUTHOR_EMAIL: "actions@github.com"
        GIT_COMMITTER_NAME: "GitHub Actions"
        GIT_COMMITTER_EMAIL: "actions@github.com"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "$GIT_AUTHOR_NAME"
        git config user.email "$GIT_AUTHOR_EMAIL"
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Update README from resume.json"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

